name: Preview Build (Reusable)

on:
  # Specify the inputs for this reusable workflow
  workflow_call:
    inputs:
      deploy:
        description: 'Deploy the preview (defaults to "false")'
        required: false
        type: boolean
        default: false
      delete:
        description: 'Delete the preview (defaults to "false")'
        required: false
        type: boolean
        default: false
      project:
        description: 'Project name (defaults to repository name)'
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      server:
        description: 'Preview server URL (defaults to "https://app.uffizzi.com")'
        required: false
        type: string
        default: https://app.uffizzi.com
      registry:
        description: 'Container registry to use (defaults to "ghcr.io")'
        required: false
        type: string
        default: ghcr.io
      images:
        description: 'Comma separated list of image key values, used when rendering the compose file (defaults to "IMAGE=organization/repository:latest")'
        required: false
        type: string
        default: IMAGE=${{ inputs.registry }}/${{ github.repository }}:latest

jobs:

  # Create a dynamic Docker Compose file for Uffizzi
  render-compose-file:
    name: Render Compose File
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      compose-file-cache-key: ${{ steps.hash.outputs.hash }}
      compose-file-cache-path: docker-compose.rendered.yml
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Render Compose File
        shell: bash
        run: |

          # Export the comma separated list of image key values as environment variables
          IMAGES="${{ inputs.images }}"
          for i in ${IMAGES//,/ }
          do
            export $i
          done

          # Substitute environment variables while creating a new docker-compose file
          envsubst < docker-compose.uffizzi.yml > docker-compose.rendered.yml
          echo "Rendered Uffizzi compose file:"
          cat docker-compose.rendered.yml
          echo "::notice::Generated rendered Docker Compose file: $(cat docker-compose.rendered.yml)"

      - name: Hash Rendered Compose File
        id: hash
        run: echo "hash=$(md5sum docker-compose.rendered.yml | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Cache Rendered Compose File
        uses: actions/cache@v3
        with:
          path: docker-compose.rendered.yml
          key: ${{ steps.hash.outputs.hash }}

  # Create and update test environments in Uffizzi when a PR is opened, updated etc.
  deploy-uffizzi-preview:
    name: Deploy Preview
    if: ${{ inputs.deploy }}
    needs: [ render-compose-file ]
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2.5.0
    with:
      compose-file-cache-key: ${{ needs.render-compose-file.outputs.compose-file-cache-key }}
      compose-file-cache-path: ${{ needs.render-compose-file.outputs.compose-file-cache-path }}
      server: ${{ inputs.server }}
      project: ${{ inputs.project }}
      ## FIXME: Can't use secrets here, only with "secrets:" below..
      # username: ${{ secrets.UFFIZZI_USERNAME }}
      username: pauli.jokela+tk@didstopia.com
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
      personal-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write

  # Delete test environments from Uffizzi when a PR is closed (merged or not)
  delete-uffizzi-preview:
    name: Delete Preview
    if: ${{ inputs.delete }}
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2.5.0
    with:
      compose-file-cache-key: ''
      compose-file-cache-path: docker-compose.rendered.yml
      server: ${{ inputs.server }}
      project: ${{ inputs.project }}
      ## FIXME: Can't use secrets here, only with "secrets:" below..
      # username: ${{ secrets.UFFIZZI_USERNAME }}
      username: pauli.jokela+tk@didstopia.com
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write

  ## TODO: Ideally refactor this, so it's more reusable and easier still customizable, as this is A LOT of copy-paste boilerplate at the moment..
  send-notification-deploy:
    name: Slack Notification
    needs: [ deploy-uffizzi-preview, delete-uffizzi-preview ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      # DEPLOYMENT

      - name: Deploy Success
        if: ${{ always() && needs.deploy-uffizzi-preview.result == 'success' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
                "attachments": [
                    {
                        "color": "#1eb80d",
                        "blocks": [
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": ":white_check_mark:  Preview Build: Deploy",
                                    "emoji": true
                                }
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": "*Successfully* _deployed_ a preview build for <https://github.com/${{ github.repository }}|${{ github.event.repository.name }}>."
                                }
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Preview Link:*\n<${{ needs.deploy-uffizzi-preview.outputs.url }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Preview Details:*\n<${{ needs.deploy-uffizzi-preview.outputs.containers_uri }}|View>"
                                    }
                                ]
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Reference:*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.event.pull_request.title || github.event.number || github.ref_name }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Action:*\n${{ github.event.action }}"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Log:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>"
                                    }
                                ]
                            },
                            {
                                "type": "divider"
                            }
                        ]
                    }
                ]
            }
        env:
          ## TODO: Switch back from the #debug channel to the #status channel when done testing
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEBUG }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      ## TODO: Apply the template from above to all of the ones below, where applicable, and note any and all variable changes!

      - name: Deploy Failure
        if: ${{ always() && needs.deploy-uffizzi-preview.result == 'failure' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
                "attachments": [
                    {
                        "color": "#de0d0d",
                        "blocks": [
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": ":x:  Preview Build: Deploy",
                                    "emoji": true
                                }
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": "*Failed* to _deploy_ a preview build for <https://github.com/${{ github.repository }}|${{ github.event.repository.name }}>!"
                                }
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Reference:*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.event.pull_request.title || github.event.number || github.ref_name }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Action:*\n${{ github.event.action }}"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Log:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>"
                                    }
                                ]
                            },
                            {
                                "type": "divider"
                            }
                        ]
                    }
                ]
            }
        env:
          ## TODO: Switch back from the #debug channel to the #status channel when done testing
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEBUG }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      # DELETION

      - name: Delete Success
        if: ${{ always() && needs.delete-uffizzi-preview.result == 'success' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
                "attachments": [
                    {
                        "color": "#1eb80d",
                        "blocks": [
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": ":white_check_mark:  Preview Build: Delete",
                                    "emoji": true
                                }
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": "*Successfully* _deleted_ a preview build for <https://github.com/${{ github.repository }}|${{ github.event.repository.name }}>."
                                }
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Reference:*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.event.pull_request.title || github.event.number || github.ref_name }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Action:*\n${{ github.event.action }}"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Log:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>"
                                    }
                                ]
                            },
                            {
                                "type": "divider"
                            }
                        ]
                    }
                ]
            }
        env:
          ## TODO: Switch back from the #debug channel to the #status channel when done testing
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEBUG }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Deploy Failure
        if: ${{ always() && needs.delete-uffizzi-preview.result == 'failure' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
                "attachments": [
                    {
                        "color": "#de0d0d",
                        "blocks": [
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": ":x:  Preview Build: Delete",
                                    "emoji": true
                                }
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": "*Failed* to _delete_ a preview build for <https://github.com/${{ github.repository }}|${{ github.event.repository.name }}>!"
                                }
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Reference:*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.event.pull_request.title || github.event.number || github.ref_name }}>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Action:*\n${{ github.event.action }}"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Build Log:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>"
                                    }
                                ]
                            },
                            {
                                "type": "divider"
                            }
                        ]
                    }
                ]
            }
        env:
          ## TODO: Switch back from the #debug channel to the #status channel when done testing
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEBUG }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
